version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "joda9"
    labels:
      - "dependencies"
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "pandas"
      - dependency-name: "plotly"
      - dependency-name: "pypsa"
      - dependency-name: "scikit-learn"
      - dependency-name: "sqlalchemy"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "joda9"
    labels:
      - "dependencies"
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "pandas"
      - dependency-name: "plotly"
      - dependency-name: "pypsa"
      - dependency-name: "scikit-learn"
      - dependency-name: "sqlalchemy"
