name: Tests with pytest

on:
  push:
    branches: 
    - dev
    - features/*
    - master
  pull_request:
    branches:
    - dev
    - features/*
    - master
  workflow_dispatch:
  
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        pip3 install -e $GITHUB_WORKSPACE[full]
        pip3 install coveralls
        pip3 install sqlalchemy==1.3.24
        pip3 install pytest
    - name: Run coverage
      run: |  
        coverage run --source=edisgo -m pytest -vv
    - name: Run coveralls
      run: |
        coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_SERVICE_NAME: github
