name: coveralls_github_actions

on:
  push:
    branches: 
    - dev
    - features/*
    - master
  pull_request:
    branches:
    - dev
    - features/*
    - master
  workflow_dispatch:
  
jobs:
  Coveralls:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: fix/#172_AtributeError
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Testing
      run: |
        pip3 install -e $GITHUB_WORKSPACE[full]
        pip3 install --upgrade coveralls
        # coverage run -m pytest
        COVERALLS_REPO_TOKEN=XpshAJmBPFQVylM82mYo74sdhduDW51Im coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_SERVICE_NAME: github-actions
